### GET ROOT
GET http://localhost:8080/ HTTP/1.1


### GET Workspaces
GET http://localhost:8080/workspaces/ HTTP/1.1
Authorization: TOKEN pt_fWEwiWeVwjlwwJiKOJsNJU_NewRz8b4e


### Create Workspaces
POST http://localhost:8080/workspaces/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDk2NTA3LCJpYXQiOjE3MTIwNjc3MDcsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.DJvS2cIuwB821PGnRkM6Asp3peU7b4-THXY9RBjjmOo
Content-Type: application/json

{
    "name": "Go Workspace 2"
}

### Make Query
POST http://localhost:8080/workspaces/3a690e9f85544f6f82e6bdc432418b11/-/queries/ HTTP/1.1
Content-Type: application/json

{
    "q": "How is the weather?"
}


### LLM Response Query Evaluation Score 1 or 0
POST http://localhost:8080/workspaces/3a690e9f85544f6f82e6bdc432418b11/-/queries/co2nkqstidu8n5uej9a0/ HTTP/1.1
Content-Type: application/json

{
    "eval": 1
}


### CUSTOMER ISSUE TOKEN
POST http://localhost:8080/workspaces/wrkco60epktidu7sod96l90/tokens/ HTTP/1.1
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMjUwNDk0LCJpYXQiOjE3MTIyMjE2OTQsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.b_bu4MxDvn6VZdsG4vtEaiPP_Z7CC4Y3EyOGyi12Plo
Authorization: TOKEN pt_fWEwiWeVwjlwwJiKOJsNJU_NewRz8b4e 

{
    "customer": {
        "externalId": "xxxx-111-zzzz",
        "email": "sanchitrrk@gmail.com",
        "phone": "+917760686068"
    },
    "create": true,
    "createBy": "email"
}


### AUTHENTICATE USER
POST http://localhost:8080/accounts/auth/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDk2NTA3LCJpYXQiOjE3MTIwNjc3MDcsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.DJvS2cIuwB821PGnRkM6Asp3peU7b4-THXY9RBjjmOo

{}


### AUTHENTICATE USER
POST http://localhost:8080/pats/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDk2NTA3LCJpYXQiOjE3MTIwNjc3MDcsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.DJvS2cIuwB821PGnRkM6Asp3peU7b4-THXY9RBjjmOo

{
    "name": "Test PAT 5",
    "description": "Test PAT 5 Description"
}


### List PATs
GET http://localhost:8080/pats/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDk2NTA3LCJpYXQiOjE3MTIwNjc3MDcsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.DJvS2cIuwB821PGnRkM6Asp3peU7b4-THXY9RBjjmOo


### List PATs
GET http://localhost:8080/pats/ HTTP/1.1
Content-Type: application/json
Authorization: Token DePC_W5yOXuOWp1WFm-Sizh6iSxRoUUh


### CUSTOMER CREATE THREAD
POST http://localhost:8080/-/threads/qa/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3b3Jrc3BhY2VJZCI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwIiwiZXh0ZXJuYWxJZCI6Inh4eHgtMTExLXp6enoiLCJlbWFpbCI6InNhbmNoaXRycmtAZ21haWwuY29tIiwicGhvbmUiOiIrOTE3NzYwNjg2MDY4IiwiaXNzIjoiYXV0aC56eWcuYWkiLCJzdWIiOiJjX2NvNjFhYmt0aWR1MXQzaTNkbjYwIiwiYXVkIjpbImN1c3RvbWVyIl0sImV4cCI6MTc0Mzc1Nzg3MSwibmJmIjoxNzEyMjIxODcxLCJpYXQiOjE3MTIyMjE4NzEsImp0aSI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwOmNfY282MWFia3RpZHUxdDNpM2RuNjAifQ.epCQ4aXvYPXIhVrX6TtfYrq0XxYXT18kIWsOae8HvUQ

{
    "query": "What is a Bengal Tiger?"
}


### CUSTOMER Thread Chat
POST http://localhost:8080/-/threads/chat/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3b3Jrc3BhY2VJZCI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwIiwiZXh0ZXJuYWxJZCI6Inh4eHgtMTExLXp6enoiLCJlbWFpbCI6InNhbmNoaXRycmtAZ21haWwuY29tIiwicGhvbmUiOiIrOTE3NzYwNjg2MDY4IiwiaXNzIjoiYXV0aC56eWcuYWkiLCJzdWIiOiJjX2NvNjFhYmt0aWR1MXQzaTNkbjYwIiwiYXVkIjpbImN1c3RvbWVyIl0sImV4cCI6MTc0Mzc1Nzg3MSwibmJmIjoxNzEyMjIxODcxLCJpYXQiOjE3MTIyMjE4NzEsImp0aSI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwOmNfY282MWFia3RpZHUxdDNpM2RuNjAifQ.epCQ4aXvYPXIhVrX6TtfYrq0XxYXT18kIWsOae8HvUQ

{
    "message": "Hi I am having trouble logging into the App. Please help!"
}


### CUSTOMER Thread Chat
POST http://localhost:8080/-/threads/chat/th_coalb9ktidud7mkk8vvg/messages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3b3Jrc3BhY2VJZCI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwIiwiZXh0ZXJuYWxJZCI6Inh4eHgtMTExLXp6enoiLCJlbWFpbCI6InNhbmNoaXRycmtAZ21haWwuY29tIiwicGhvbmUiOiIrOTE3NzYwNjg2MDY4IiwiaXNzIjoiYXV0aC56eWcuYWkiLCJzdWIiOiJjX2NvNjFhYmt0aWR1MXQzaTNkbjYwIiwiYXVkIjpbImN1c3RvbWVyIl0sImV4cCI6MTc0Mzc1Nzg3MSwibmJmIjoxNzEyMjIxODcxLCJpYXQiOjE3MTIyMjE4NzEsImp0aSI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwOmNfY282MWFia3RpZHUxdDNpM2RuNjAifQ.epCQ4aXvYPXIhVrX6TtfYrq0XxYXT18kIWsOae8HvUQ

{
    "message": "can you help me with this issue? I've been trying to debug it for hours and I can't figure out what's wrong. I've checked all the logs and error messages, but nothing seems to be indicating the problem. I've also tried searching online for similar issues, but couldn't find any relevant solutions. It's really frustrating and I'm running out of ideas. Any help would be greatly appreciated. Thank you!"
}


### CUSTOMER Thread Chat
GET http://localhost:8080/-/threads/chat/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3b3Jrc3BhY2VJZCI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwIiwiZXh0ZXJuYWxJZCI6Inh4eHgtMTExLXp6enoiLCJlbWFpbCI6InNhbmNoaXRycmtAZ21haWwuY29tIiwicGhvbmUiOiIrOTE3NzYwNjg2MDY4IiwiaXNzIjoiYXV0aC56eWcuYWkiLCJzdWIiOiJjX2NvNjFhYmt0aWR1MXQzaTNkbjYwIiwiYXVkIjpbImN1c3RvbWVyIl0sImV4cCI6MTc0Mzc1Nzg3MSwibmJmIjoxNzEyMjIxODcxLCJpYXQiOjE3MTIyMjE4NzEsImp0aSI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwOmNfY282MWFia3RpZHUxdDNpM2RuNjAifQ.epCQ4aXvYPXIhVrX6TtfYrq0XxYXT18kIWsOae8HvUQ



### CUSTOMER Thread Chat
GET http://localhost:8080/-/threads/chat/th_coalb9ktidud7mkk8vvg/messages/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3b3Jrc3BhY2VJZCI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwIiwiZXh0ZXJuYWxJZCI6Inh4eHgtMTExLXp6enoiLCJlbWFpbCI6InNhbmNoaXRycmtAZ21haWwuY29tIiwicGhvbmUiOiIrOTE3NzYwNjg2MDY4IiwiaXNzIjoiYXV0aC56eWcuYWkiLCJzdWIiOiJjX2NvNjFhYmt0aWR1MXQzaTNkbjYwIiwiYXVkIjpbImN1c3RvbWVyIl0sImV4cCI6MTc0Mzc1Nzg3MSwibmJmIjoxNzEyMjIxODcxLCJpYXQiOjE3MTIyMjE4NzEsImp0aSI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwOmNfY282MWFia3RpZHUxdDNpM2RuNjAifQ.epCQ4aXvYPXIhVrX6TtfYrq0XxYXT18kIWsOae8HvUQ



### CUSTOMER Thread Chat
GET http://localhost:8080/-/me/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ3b3Jrc3BhY2VJZCI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwIiwiZXh0ZXJuYWxJZCI6Inh4eHgtMTExLXp6enoiLCJlbWFpbCI6InNhbmNoaXRycmtAZ21haWwuY29tIiwicGhvbmUiOiIrOTE3NzYwNjg2MDY4IiwiaXNzIjoiYXV0aC56eWcuYWkiLCJzdWIiOiJjX2NvNjFhYmt0aWR1MXQzaTNkbjYwIiwiYXVkIjpbImN1c3RvbWVyIl0sImV4cCI6MTc0Mzc1Nzg3MSwibmJmIjoxNzEyMjIxODcxLCJpYXQiOjE3MTIyMjE4NzEsImp0aSI6Indya2NvNjBlcGt0aWR1N3NvZDk2bDkwOmNfY282MWFia3RpZHUxdDNpM2RuNjAifQ.epCQ4aXvYPXIhVrX6TtfYrq0XxYXT18kIWsOae8HvUQ



### CUSTOMER Thread Chat
POST http://localhost:8080/workspaces/wrkco60epktidu7sod96l90/threads/chat/th_coelr0ktidu1s2iaj770/messages/ HTTP/1.1
Content-Type: application/json
Authorization: TOKEN pt_fWEwiWeVwjlwwJiKOJsNJU_NewRz8b4e 

{
    "message": "Member: M1 Message!"
}
