### GET ROOT
GET http://localhost:8080/ HTTP/1.1


### GET Workspaces
GET http://localhost:8080/workspaces/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDY2NzUxLCJpYXQiOjE3MTIwMzc5NTEsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.H3G3Q9SglR9hPXMleefPWSCdwbGLhtvvlN_GsvFT_Wg


### Make Query
POST http://localhost:8080/workspaces/3a690e9f85544f6f82e6bdc432418b11/-/queries/ HTTP/1.1
Content-Type: application/json

{
    "q": "How is the weather?"
}


### LLM Response Query Evaluation Score 1 or 0
POST http://localhost:8080/workspaces/3a690e9f85544f6f82e6bdc432418b11/-/queries/co2nkqstidu8n5uej9a0/ HTTP/1.1
Content-Type: application/json

{
    "eval": 1
}


### CUSTOMER ISSUE TOKEN
POST http://localhost:8080/workspaces/3a690e9f85544f6f82e6bdc432418b11/tokens/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDY2NzUxLCJpYXQiOjE3MTIwMzc5NTEsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.H3G3Q9SglR9hPXMleefPWSCdwbGLhtvvlN_GsvFT_Wg

{
    "customer": {
        "externalId": "xxxx-111-zzzz",
        "email": "sanchitrrk@gmail.com",
        "phone": "+917760686068"
    },
    "create": true,
    "createBy": "email"
}


### AUTHENTICATE USER
POST http://localhost:8080/accounts/auth/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDY2NzUxLCJpYXQiOjE3MTIwMzc5NTEsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.H3G3Q9SglR9hPXMleefPWSCdwbGLhtvvlN_GsvFT_Wg

{}


### AUTHENTICATE USER
POST http://localhost:8080/pats/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDY2NzUxLCJpYXQiOjE3MTIwMzc5NTEsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.H3G3Q9SglR9hPXMleefPWSCdwbGLhtvvlN_GsvFT_Wg

{
    "name": "Test PAT 5",
    "description": "Test PAT 5 Description"
}


### List PATs
GET http://localhost:8080/pats/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IlJiUGhDZzFKTEV6dDNYbG8iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzEyMDY2NzUxLCJpYXQiOjE3MTIwMzc5NTEsImlzcyI6Imh0dHBzOi8vdHdqbGxqdmltb21nb29jcm5pZWwuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjYyMmZkNDFjLWE0MzctNGNiMi1iMTNkLThjOTdjZmRjNTYyZiIsImVtYWlsIjoic2FuY2hpdHJya0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7fSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcwNzMxMzUxOH1dLCJzZXNzaW9uX2lkIjoiNDY2NjIwOGQtOGI1Mi00ODBiLThmYTUtOGU2N2Y5MDM1ODI0IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.H3G3Q9SglR9hPXMleefPWSCdwbGLhtvvlN_GsvFT_Wg


### List PATs
GET http://localhost:8080/pats/ HTTP/1.1
Content-Type: application/json
Authorization: Token DePC_W5yOXuOWp1WFm-Sizh6iSxRoUUh
