# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: converse.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63onverse.proto\x12\x08\x63onverse\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"!\n\rQueryResponse\x12\x10\n\x08response\x18\x01 \x01(\t2H\n\x0cQueryService\x12\x38\n\x05Query\x12\x16.converse.QueryRequest\x1a\x17.converse.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'converse_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUERYREQUEST']._serialized_start=28
  _globals['_QUERYREQUEST']._serialized_end=57
  _globals['_QUERYRESPONSE']._serialized_start=59
  _globals['_QUERYRESPONSE']._serialized_end=92
  _globals['_QUERYSERVICE']._serialized_start=94
  _globals['_QUERYSERVICE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
