import { Inter } from "next/font/google";
import { ReactQueryClientProvider } from "@/components/providers";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <div className="flex flex-col min-h-screen">{children}</div>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
